language: java
jdk:
  - openjdk8

sudo: false
install: true

script:
  - pwd
  - cd webapp
  - ./gradlew war
  - cd build/libs
  - ls -al
  - cd ../../..
  - pwd
  - ls -al

language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- cd webapp
- ./gradlew war
- ./gradlew build
after_success:
- mkdir codedeploy
- zip -r csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
- ls -al
- mv csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- cd ..
deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  local_dir: codedeploy
  bucket: $s3_bucket
  region: us-east-1
  skip_cleanup: true
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: $s3_bucket
  key: csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip
  bundle_type: zip
  application: $application
  deployment_group: $deployment_group
  region: us-east-1
  wait-until-deployed: true
  on:
    all_branches: true

notifications:
  email:
    recipients:
      - liu.junyu@husky.neu.edu
