language: java
jdk:
  - openjdk8

sudo: false
install: true

script:
  - cd webapp
  - ./gradlew war
  - ./gradlew build

notifications:
  email:
    recipients:
      - hu.ziy@husky.neu.edu
